config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :flats do
    resources :bookings, only: [:create, :new, :edit, :update, :destroy]
    resources :reviews, only: [ :new, :create ]
  end

  resources :bookings, except: [:create, :new]
  resources :reviews, only: [ :destroy ]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :flat

end

app/models/flat.rb
class Flat < ApplicationRecord
  has_many_attached :photos
  validates :photos, :name, :address, :price, presence: true
  belongs_to :user
  has_many :bookings
  has_many :reviews, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_address,
  against: [ :address ],
  using: {
    tsearch: { prefix: true } 
  }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :flat
  belongs_to :user

  validates :content, length: { minimum: 20 }
  validates :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :flats, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_user!
   before_action :store_user_location!, if: :storable_location?
   before_action :configure_permitted_parameters, if: :devise_controller?

   def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    # For additional in app/views/devise/registrations/edit.html.erb
     devise_parameter_sanitizer.permit(:account_update, keys: [:name])
   end

   def after_sign_in_path_for(resource_or_scope)
     stored_location_for(resource_or_scope) || super
   end

   def storable_location?
      request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
   end

   def store_user_location!
      # :user is the scope we are authenticating
      store_location_for(:user, request.fullpath)
   end
end

app/controllers/booking_controller.rb
class BookingController < ApplicationController
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.where(user: current_user)
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
    @flat = Flat.find(params[:flat_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @flat = Flat.find(params[:flat_id])
    # start_date = params[:booking][:start_date].gsub(" ","")
    # end_date = params[:booking][:end_date].gsub(" ","")
    # @booking.start_date = Date.strptime(start_date,'%m/%d/%Y')
    # @booking.end_date = Date.strptime(end_date,'%m/%d/%Y')
    @booking.flat = @flat
    @booking.user = current_user

    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/flat_controller.rb
class FlatController < ApplicationController
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

def index
  if params[:search].present?
    if params[:search][:query].present?
      @flats = Flat.search_by_address(params[:search][:query]).geocoded
    else
      @flats = Flat.all.geocoded
    end
  else
    @flats = Flat.all.geocoded
  end

    @markers = @flats.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { flat: flat })
      }
    end
end

def new
  @flat = Flat.new
end

def create
  @flat = Flat.new(flat_params)
  @flat.user = current_user
  if @flat.save
    redirect_to flat_path(@flat)
  else
    render :new
  end
end

def show
  @flat = Flat.find(params[:id])
  @review = Review.new
end

def edit
  @flat = Flat.find(params[:id])
end

def update
  @flat = Flat.find(params[:id])
  @flat.update(flat_params)

  if @flat.save
      redirect_to flat_path(@flat)
  else
      render :new
  end
end


private

def flat_params
  params.require(:flat).permit(:name, :address, :description, :price, :pool, :wifi, :speakers, :smoking, :icemaker, :cleaner, photos: [])
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @flat = Flat.find(params[:flat_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    # we need `restaurant_id` to associate review with corresponding restaurant
    @flat = Flat.find(params[:flat_id])
    @review.flat = @flat
    @review.user = current_user
    if @review.save
      redirect_to flat_path(@flat, anchor: "review-#{@review.id}")
    else
      render 'flats/show'
    end
  end


  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to flat_path(@review.flat)
  end


  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  @user = User.name
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container">
  <h1>My Bookings</h1>
  <div class="row">
    <% @bookings.each do |booking| %>
      <div class="col-6 my-2">
        <div class="card-trip">
<!--           <img src="https://images.unsplash.com/photo-1524397057410-1e775ed476f3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80" />
 -->          <%= cl_image_tag booking.flat.photos[0].key, crop: :fill %>
          <div class="card-trip-infos">
            <div>
                <h3><%= link_to "#{booking.flat.name}", booking_path(booking) %></h3>
                <p><%= "#{booking.start_date.to_formatted_s(:short)} - #{booking.end_date.to_formatted_s(:short)}" %></p>
                <% number_of_days = booking.end_date - booking.start_date %>
                <p><%= "#{number_of_days.to_i} nights @ £#{booking.flat.price} per night" %></p>
                <p class="card-text"><%= "£#{number_of_days.to_i * booking.flat.price} total price" %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container mx-auto my-auto" style="width: 18rem;">
  <div class="card" style="width: 18rem;">
    <%= cl_image_tag @booking.flat.photos[0].key, crop: :fill, class: "card-img-top" %>
    <div class="card-body">
      <h5 class="card-title p-2" style="font-size: 20px; font-weight: bold; text-align: center;"><%= "Your booking at #{@booking.flat.name}" %></h5>
      <p class="card-text" style="text-align: center"><%= "#{@booking.start_date.to_formatted_s(:short)} - #{@booking.end_date.to_formatted_s(:short)}" %></p>
      <% number_of_days = @booking.end_date - @booking.start_date %>
      <p class="card-text" style="text-align: center"><%= "#{number_of_days.to_i} nights @ £#{@booking.flat.price} per night" %></p>
      <p class="card-text" style="text-align: center"><%= "£#{number_of_days.to_i * @booking.flat.price} total price (exc service)" %></p>
    </div>
      <%= link_to "Back to #{@booking.flat.name}", flat_path(@booking.flat), class: "btn btn-outline-secondary my-2 mx-4" %>
      <%= link_to "Back to All Bookings", bookings_path, class: "btn btn-outline-primary my-2 mx-4" %>
      <%= link_to "Delete Booking", booking_path(@booking), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger my-2 mx-4" %>
        <a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/restaurants/2"></a>
    </div>

</div>

app/views/flats/_info_window.html.erb
<%= cl_image_tag flat.photos[0].key %>
<div class="container">
  <h2><%= flat.name %></h2>
  <p><%= flat.address %></p>
</div>

app/views/flats/edit.html.erb
<div class="container-fluid bg-light py-3">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <div class="card card-body">
        <h3 class="text-center mb-4">Edit Your Listing</h3>
          <div class="container">
            <%= simple_form_for(@flat) do |f| %>
              <%= f.input :name %>
              <%= f.input :address %>
              <%= f.input :description %>
              <%= f.input :price %>
              <p> Pool <%= f.check_box :pool %> &nbsp&nbsp&nbsp Speakers <%= f.check_box :speakers %> &nbsp&nbsp&nbsp Cleaner <%= f.check_box :cleaner %> </p>
              <p> Wifi  <%= f.check_box :wifi %> &nbsp&nbsp&nbsp Smoking <%= f.check_box :smoking %> &nbsp&nbsp&nbsp Ice Maker <%= f.check_box :icemaker %> </p>
              <%= f.input :photos, as: :file, input_html: { multiple: true } %>
              <label class="small">
                  <input name="terms" type="checkbox">I have read and agree to the <a href="#">terms of service</a>
              </label>
              <%= f.submit class: "btn btn-lg btn-primary btn-block" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<section class ="flat-index">
  <div class="flat-cards">
      <%= simple_form_for :search, url: flats_path, method: :get do |f| %>
      <div class="search-form-control form-group">
        <input class="form-control string required" type="text" name="search[query]" id="search_query" />
        <button name="button" type="submit" class="btn btn-flat">
        <i class="fas fa-search" id="search"></i> Search
        </button>
        <% end %>
      </div>

  <% @flats.each do |flat| %>
    <div class="card-product my-2">
     
      <%= cl_image_tag flat.photos[0].key, crop: :fill %>
        <div class="card-product-infos">
          <h5><%= link_to "#{flat.name}", flat_path(flat)%></h5>
          <p><%= flat.description %></p>
          <p class="card-product-price">£<%= flat.price %> per night</p>
        </div>
      </div>
    <% end %>
  </div>
  <div class="map-index" id="map"
     style= "height: 600px; width: 50%;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</section>

app/views/flats/new.html.erb
<div class="container-fluid bg-light py-3">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <div class="card card-body">
        <h3 class="text-center mb-4">Create your Listing</h3>
          <div class="container">
            <%= simple_form_for(@flat) do |f| %>
              <%= f.input :name %>
              <%= f.input :address %>
              <%= f.input :description %>
              <%= f.input :price %>
              <p> Pool <%= f.check_box :pool %> &nbsp&nbsp&nbsp Speakers <%= f.check_box :speakers %> &nbsp&nbsp&nbsp Cleaner <%= f.check_box :cleaner %> </p>
              <p> Wifi  <%= f.check_box :wifi %> &nbsp&nbsp&nbsp Smoking <%= f.check_box :smoking %> &nbsp&nbsp&nbsp Ice Maker <%= f.check_box :icemaker %> </p>
              <%= f.input :photos, as: :file, input_html: { multiple: true } %>
              <div>
                <!-- <label class="small">
                    <input name="terms" type="checkbox">I have read and agree to the <a href="#">terms of service</a>
                </label> -->
              </div>
              <%= f.submit "Submit Listing", class: "btn btn-lg btn-primary btn-block" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
 <!--Carousel Wrapper-->
<div class="carousel-container mx-auto">
   <div id="carousel-example-1z" class="carousel slide carousel-fade" data-ride="carousel">
     <!--Indicators-->
     <ol class="carousel-indicators">
      <% @flat.photos.each do |photo| %>
      <% if photo == @flat.photos[0] %>
         <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
       <% else %>
         <li data-target="#carousel-example-1z" data-slide-to="1"></li>
       <% end %>
       <% end  %>
     </ol>

     <div class="carousel-inner" role="listbox">

       <% @flat.photos.each do |photo| %>
       <% if photo == @flat.photos[0] %>
       <div class="carousel-item active">
        <% else %>
       <div class="carousel-item">
        <% end %>
        <%= cl_image_tag photo.key, crop: :fill, class: "d-block w-100" %>
       </div>
       <% end %>
     </div>


     <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
       <span class="carousel-control-prev-icon" aria-hidden="true"></span>
       <span class="sr-only">Previous</span>
     </a>
     <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
       <span class="carousel-control-next-icon" aria-hidden="true"></span>
       <span class="sr-only">Next</span>
     </a>
     <!--/.Controls-->
   </div>

 <!--/.Carousel Wrapper-->

<div class="container mt-4 mx-auto" style="width:100%">
  <div class="row">
    <div class="col-8">
      <div class="card" style="height:90%">
        <div class="card-body">
          <div class="title-box">
            <h5 class="card-title"><%= @flat.name %></h5>
          </div>
          <h6 class="card-subtitle p-0 mb-2 text-muted" style="text-align: left;"><%= @flat.address %></h6>
          <p class="card-text"><%= @flat.description %></p>

        <% if current_user == @flat.user %>
          <%= link_to "Edit Flat", edit_flat_path(@flat), class: "btn btn-outline-secondary btn-sm" %>
        <% else  %>
        <% end %>
          <!-- <a href="#" class="card-link">Card link</a>
          <a href="#" class="card-link">Another link</a> -->
        </div>
      </div>
    </div>
    <div class="col-4">
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">Booking</h5>
          <%= simple_form_for([@flat, Booking.new]) do |f| %>
            <%= f.input :start_date, input_html: { id: "startdate" }, as: :string, autocomplete: 'off' %>
            <%= f.input :end_date, input_html: { id: "enddate" }, as: :string, autocomplete: 'off' %>
            <h6 class="card-subtitle mb-2 text-muted">
            £<%= @flat.price %> per night
            </h6>
            <div class="costs costs-hidden" data-rate="<%= @flat.price.to_json %>">
              <table class="table">
                <tr>
                  <td>£<%= @flat.price %> x <span id="days">0</span> days</td>
                  <td class="text-right">£<span id="price">0</span></td>
                </tr>
                <tr>
                  <td>Service fee</td>
                  <td class="text-right">£<span id="service-fee">0</span></td>
                </tr>
                <tr>
                  <td><strong>Total</strong></td>
                  <td class="text-right">£<span id=total-price>0</span></td>
                </tr>
              </table>
            </div>
            <h6> <%= f.submit class: "btn btn-primary mb-2 mx-auto"%> </h6>
          <% end %>
          <p id="charged" class="card-subtitle mb-2 text-muted">(You won't be charged yet)</p>
        </div>
      </div>
    </div>
  </div>
  <div class="row" id="facilities-div">
    <div class="col-8">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"> Facilities </h5>
          <div class="facilities-container">
            <div class="facilities-boxes">
              <% if @flat.pool == true  %>
              <p class="card-text"> Pool <i id="true" class="fas fa-check-circle"></i></p>
              <% else %>
              <p class="card-text"> Pool <i class="fas fa-times-circle"></i> </p>
              <% end %>
              <% if @flat.wifi == true  %>
              <p class="card-text"> Wifi <i id="true" class="fas fa-check-circle"></i></p>
              <% else %>
              <p class="card-text"> Wifi <i class="fas fa-times-circle"></i></p>
              <% end %>
            </div>
            <div class="facilities-boxes">
              <% if @flat.cleaner == true  %>
              <p class="card-text"> Cleaner <i id="true" class="fas fa-check-circle"></i></p>
              <% else %>
              <p class="card-text"> Cleaner <i class="fas fa-times-circle"></i></p>
              <% end %>
              <% if @flat.speakers == true  %>
              <p class="card-text"> Speakers <i id="true" class="fas fa-check-circle"></i></p>
              <% else %>
              <p class="card-text"> Speakers <i class="fas fa-times-circle"></i></p>
              <% end %>
            </div>
            <div class="facilities-boxes">
              <% if @flat.smoking == true  %>
              <p class="card-text"> Smoking <i id="true" class="fas fa-check-circle"></i></p>
              <% else %>
              <p class="card-text"> Smoking <i class="fas fa-times-circle"></i></p>
              <% end %>
              <% if @flat.icemaker == true  %>
              <p class="card-text"> Ice Maker <i id="true" class="fas fa-check-circle"></i></p>
              <% else %>
              <p class="card-text"> Ice Maker <i class="fas fa-times-circle"></i></p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
 <div class="reviews">
  <div class="row">
    <div class="col-8">
      <div class="card">
        <div class="card-body">
         <% if @flat.reviews.any? %>
           <% star = [] %>
             <% @flat.reviews.each do |review| %>
             <% star << review.rating %>
             <% end %>
               <% if star.size > 0 %>
                 <% final_rating = star.inject{ |sum, el| sum + el }.to_f / star.size %>
               <% else %>
               <% end  %>
             <div><h5 class="card-title"> Reviews
                  <% if final_rating %>
                    <% final_rating.to_i.times do %>
                  <i id="star" class="fas fa-star"></i>
                  <% end %>
                    <% if final_rating % 2 == 0 %>
                      <i></i>
                    <% elsif final_rating % 2 == 1  %>
                      <i></i>
                    <% else %>
                    <i id="star" class="fas fa-star-half"></i>
                    <% end %>
                  <% else %>
                  <% end %>
                </h5>
          <p id="leave-review"> <%= link_to 'Leave a review', flat_path(@flat, anchor: "reviewnew-") %> </p></div>
          <br>
          <% else %>
            <div><h5 class="card-title"> No reviews yet
            <p id="leave-review"> <%= link_to 'Be the first to leave a review', flat_path(@flat, anchor: "reviewnew-") %> </p></div>
          <% end  %>
          <div>
              <% @flat.reviews.each do |review| %>
                <p id="review-<%= review.id %>"> - <%= review.content %></p>
                 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <% review.rating.to_i.times do  %>
                 <i id="star" class="fas fa-star"></i>
                <% end %>
                <% if review.user.name  %>
                  <p id="reviewer"><%= review.user.name %><p>
                  <% else %>
                <% end  %>
                <br>
                <br>
              <% end %>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
        <div>
          <div>
            <div>
              <div class="row" id="leave-review">
                <div class="col-md-8 mx-left">
                  <div class="card card-body">
                    <h5 class="mb-4" id="reviewnew-"> &nbsp; Leave a review of <%=@flat.name %>!</h5>
                    <div class="container">
                      <%= simple_form_for [ @flat, @review ], remote: true do |f| %>
                      <%= f.input :content, :label => "How was your stay, #{current_user.name}?" %>
                      <%= f.input :rating, collection: (1..5) %>
                      <%= f.submit "Submit review", class: "btn btn-primary" %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
         </div>
      </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRentEventFlats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

  </head>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  <body>
    <div class="total-navbar">
      <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
        <%= link_to root_path do  %>
            <img class="navbar-brand" src="https://image.shutterstock.com/image-vector/house-logo-template-design-vector-260nw-741515455.jpg" />
        <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>


        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <%= link_to "Home", root_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <% if user_signed_in?  %>
              <%= link_to "List a Property", new_flat_path, class: "nav-link" %>
                <% else %>
              <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
              <% end %>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/bookings">My Bookings</a>
            </li>
            <li class="nav-item dropdown">
              <% if user_signed_in?  %>
              <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://i1.sndcdn.com/artworks-000524215752-qk19wd-t500x500.jpg" />
              <% else %>
              <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://lh3.googleusercontent.com/proxy/v4a-aWvCkuOUR4CQ7soGkfdpaAoaxC07HZg6Vu3X77AF0mbC64OYrV2kNbiFGwD56PrPSnHW5OgpEd1yaprR9L_qJBvRMjmuzbauo7XaWpyVfKMLp11QLp3dPThmYCJ9BcEx" />
              <% end %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="min-height">
      <%= yield %>
    </div>
    <div class="footer">
      <div class="footer-links">
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
      </div>
      <div class="footer-copyright">
        Team Socialite <i class="fas fa-heart"></i>
      </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1523301343968-6a6ebf63c672?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80);">
  <div class="container">
    <h1>Socialite</h1>
    <p>Find the best <span id="js-typed-text"></span>for any occasion</p>
    <div class="container mt-10">
      <form novalidate="novalidate" class="simple_form search" action="/flats" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="&#x2713;" />
        <div class="search-form-control form-group" id="homepage_search">
          <input class="form-control string required" type="text" name="search[query]" id="search_query" />
          <button name="button" type="submit" class="btn btn-flat">
            <i id="search" class="fas fa-search"></i> Search
          </button>
        </div>
      </form>
    </div>
    <a href="/flats" class="btn btn-primary">View Listings</a>
  </div>
</div>